### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by redwik** [tiltom/PV247-Expense-manager#58]
Add a test name when new test is created

**Comment by redwik** [comment]
ColorGeneratorServiceTest -
ValidateModel_NegativeIndex_ReturnTheSameColorAsForPositiveIndex
CategoryServiceTest - ValidateCategory_EmptyDescription_ReturnFalse
CategoryServiceTest - ValidateCategory_EmptyName_ReturnFalse
CategoryServiceTest - ValidateCategory_NotSupportedGlyphicon_ReturnFalse
CategoryServiceTest - ValidateCategory_NullCategory_ReturnFalse

**Comment by SlavoKrupa** [comment]
ColorGeneratorServiceTest
- ValidateModel_SameIndexSameColor_ReturnSameColorForSameIndex
- ValidateModel_NewColor_ReturnNewColorWhenCalledMultipleTimes
- ValidateModel_NegativeIndex_ReturnTheSameColorAsForPositiveIndex
- ValidateModel_ColorStartsWithSharp_Color
- ValidateModel_ColorHave7Char_Color
