### ISSUE TITLE
deploy to azure

### ISSUE THREAD

**Issue by Pebin** [tiltom/PV247-Expense-manager#61]

**Comment by tiltom** [comment]
Successfully published to Azure (fancyexpensemanager.azurewebsites.net) but unable to start because of missing DB.

**Comment by PetrSvirak** [comment]
Your connection string goes as follows:
`Server=tcp:pv247.database.windows.net,1433;Database=ExpenseManager;User ID={your_username_here};Password={your_password_here};Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;`

Username and passowrd will be provided another way.

**Comment by tiltom** [comment]
Working :dancers: ! But I had to use a little "hack" on DB: http://www.alextells.com/missing-stored-procedure-sys-sp_msforeachtable-azure-sql-database/ .

**Comment by PetrSvirak** [comment]
Don't be shy with Your product, after closing (~ solving) #80, promote Your address to the ``README.md`` or at least WIKI ;-)
