### ISSUE TITLE
add scheduler

### ISSUE THREAD

**Issue by Pebin** [tiltom/PV247-Expense-manager#62]

**Comment by PetrSvirak** [comment]
I come by this interesting article:
https://azure.microsoft.com/en-us/documentation/articles/app-insights-monitor-web-app-availability/ – regular requests to a given page might be just what you want.

Here are some other services, just in case your account does not allow availability tests:
* http://www.monitor.us/
* http://www.siteuptime.com/
* http://www.host-tracker.com/ 
* https://www.uptrends.com (trial)
BTW: The services require an email in exchange for the free service, so I strongly suggest considering either an well-known account from http://bugmenot.com/ or creating a temporary account at https://mailinator.com/ (or other similar services).

**Comment by Pebin** [comment]
transactions are now add on pings from http://www.monitor.us/
