### ISSUE TITLE
Update seeding data

### ISSUE THREAD

**Issue by strho** [tiltom/PV247-Expense-manager#80]
Seeding data has t o be updated. For example, all transactions for admin user have to be in same currency as wallet because there is no transformation when seeding method is ran.

**Comment by PetrSvirak** [comment]
You should also separate "test" and "production" seeding. It is not necessary to have production seeding context, however, I would be good to have one, so you can eventually update DB schema easily no, that you are on-line. Put your on-line DB to a good state and create "initial migration", so you have something to start with (you have to use correct connection string in the web.config of course).

Also, there should be no accounts in "production" seeding, so whole your azure application cannot be hijacked after reading a code for seeding context (you either have to write code that registers first user as administrator (accepting that no users means application was just deployed for the first time and that you are OK with all (security) risks) or ensure that seeding accounts are inactivated in live environment.

**Comment by redwik** [comment]
Just a question: what should be in the production seeding? In my opinion, only currencies (as we can't create a new one on the site) and admin user you wrote about. Or am I missing something?

**Comment by PetrSvirak** [comment]
Yep. You're right. Sometimes, there are also several users and data for "on site" testing (so one does not need existing/real just account to confirm an issue).

These accounts are usually disabled by a flag that can be set in DB only - sort of readonly field in DB model (provider will not allow to change the field's value of any model when setting changes).

**Comment by PetrSvirak** [comment]
After the conversation related to issue #97, it is OK to only change seeded users' passwords and close this issue. Unless you decide not to follow my suggestion in the conversation mentioned above, it is not necessary to deliver me the new passwords.

**Comment by PetrSvirak** [comment]
Hm, do change passwords for all seeded (pre-generated) users in the same manner you did for administrator – I hoped this would be obvious. Otherwise, it looks good.
