### ISSUE TITLE
Automatic currency recalculation bug

### ISSUE THREAD

**Issue by redwik** [tiltom/PV247-Expense-manager#88]
I created new transaction, my wallet currency was dollar, and amount was 7. Then I edited my wallet currency to CZK and the transaction amount was 173887.00. I suppose this is not right (if this is OK, I could buy an island :-D)

**Comment by Lajcisvk** [comment]
Locally it works OK, problem is only at azure. It also sometimes throws Attempt to divide by zero exception when changing wallet currency on server.

**Comment by PetrSvirak** [comment]
Have you tried it locally in release mode without debugger attached? It might be similar problem as in #85.

**Comment by strho** [comment]
The problem was the decimal number format. It was expecting xxx.xxx and from web we've got xxx,xxx (comma vs. period in decimal numbers)
