### ISSUE TITLE
Remove TODOs from code

### ISSUE THREAD

**Issue by PetrSvirak** [tiltom/PV247-Expense-manager#90]
Search trough the solution are remove all TODO comments that remain. I do not mean only to remove the comments of course. Rather make TO DO become DONE ;-)

**Comment by redwik** [comment]
TODOs:
BudgetAccessRightService - DeleteBudgetAccessRight
CategoryService - GetGlyphicons
WalletService - EditWallet
RegisterContexts - Register
some TODOs in *.js files (I suppose this is nothing we should care about)
