### ISSUE TITLE
Prepare azure instance for presentation

### ISSUE THREAD

**Issue by PetrSvirak** [tiltom/PV247-Expense-manager#91]
This should be discussed in more details and completely in your hands, however, you will have to create some data (transfers) and users to backup your use-cases during the presentation. Elaborate (in this issue or on WIKI, so it can easily be tracked) what actual use-cases will you present and what data will you need.

Each use-case should include at least several bullets from your assignment (so you do not have too much use-cases, but you show quite everything you have) – there should definitely be new registration and wallet sharing, nicely looking graphs, transaction addition, currency conversion and budgets.

Be prepare that there might be so questions regarding what's the difference and purpose of budget and wallet and why is there only one wallet and multiple budgets, … – you can prepare a short presentation to show high-level design (management-wise images with some pointed arrows, wallets, purses (~ budgets), airplane tickets, hamburgers and Statues of Liberty…) – no more than 5 slides to introduce your core ideas (slides should be accessible on Wiki, as an browser will be only thing available to you during the presentation)

You know the drill: graphs have to be diverse and shiny, transactions has to look so plenty a millionaire dies of jealousy and uninterested women have to faint only by seeing your integration with Google and Facebook – there are StarWars tickets at stake! → so be like [this](http://i.dailymail.co.uk/i/pix/2015/10/20/23/2D9B66E500000578-3281767-image-a-18_1445379849349.jpg), rather than getting into [this](https://i.imgflip.com/sty9r.jpg) :grinning:

**Comment by Pebin** [comment]
It's done. All millionaires died of jealousy and we've got all the women for us now!
